---
- hosts: lampserver
  become: true
  gather_facts: false

  vars_files:
    - vars.yml

  pre_tasks:
    - include: tasks/pre.yml

  handlers:
    - include: handlers/handlers.yml

  tasks:
    - include: tasks/commom.yml
    - include: tasks/apache.yml
    - include: tasks/mysql.yml
    - include: tasks/composer.yml
    - include: tasks/drush.yml
    - include: tasks/drupal.yml